name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.9.0
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'
    - name: Clean npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Run tests
      run: npm test

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}